Hello world using wikipedia text of Hello World
DaylightFox/HelloRube pull request #113
Opened 2019-10-01 11:24 UTC by LarryShamalama

Here's my attempt

2019-10-01 14:05 UTC, DaylightFox requested changes

2019-10-01 14:05 UTC, DaylightFox commented on Python/hello_hello_world.py
> +# print(''.join(list(dictionary.values())))
Looks great! Had a little giggle;)

The only thing I need you to do before I merge this is for you to remove this commented line:
```suggestion

```
Looks like it was only there for testing;)

2019-10-01 16:04 UTC, LarryShamalama commented
Done, thanks a lot!

2019-10-02 10:54 UTC, DaylightFox commented
Great, thanks! Great contribution. Merged :)

2019-10-02 10:54 UTC, merged